### ISSUE TITLE
Error installing on HDP 2.3 on node running RHEL 6.5

### ISSUE THREAD

**Issue by dasgoll** [randerzander/ipython-service#6]
I'm getting this error when trying to install the service:

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/jupyter-service/package/scripts/ambari/master.py", line 41, in <module>
    Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 218, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/jupyter-service/package/scripts/ambari/master.py", line 9, in install
    helpers.add_repos()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/jupyter-service/package/scripts/ambari/ambari_helpers.py", line 13, in add_repos
    for repo in os.listdir(repo_dir):
UnboundLocalError: local variable 'repo_dir' referenced before assignment

**Comment by azimut** [comment]
Any know workaround for this?

**Comment by azimut** [comment]
I debug a little and it seems that the issue is on `https://github.com/randerzander/jupyter-service/blob/master/package/scripts/ambari/ambari_helpers.py#L9` and the value returned there. On centos return "CentOS Linux".

**Comment by ghost** [comment]
I hit this error as well, for a workaround I set the directory variables globally. 

Once I did this the installation proceeded

repo_dir = package_dir()+'files/repos/rhel6/'
os_repo_dir = '/etc/yum.repos.d/'

def add_repos():
  global repo_dir
  global os_repo_dir
  #distribution = platform.linux_distribution()[0].lower()
  #TODO: add ubuntu
  #if distribution in ['centos', 'redhat'] :
    #repo_dir = package_dir()+'files/repos/rhel6/'
    #os_repo_dir = '/etc/yum.repos.d/'

**Comment by minkymorgan** [comment]
@brownbullet, this also worked for me. thanks!
